"""suite output dir

Revision ID: efe3a33a9569
Revises: f882a8ae5938
Create Date: 2026-07-31 13:27:39.714812
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'efe3a33a9569'
down_revision: str | None = 'f882a8ae5938'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_suites', sa.Column('output_dir', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_suites', 'output_dir')
    # ### end Alembic commands ###
