"""generated test suites cases steps files

Revision ID: f882a8ae5938
Revises: 4c6d8b58987e
Create Date: 2026-07-31 12:34:53.843740
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'f882a8ae5938'
down_revision: str | None = '4c6d8b58987e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_suites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('recording_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('recording', 'agent', 'manual', name='case_source'), nullable=False),
    sa.Column('generator', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recording_id'], ['recording_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_suites_project_id'), 'test_suites', ['project_id'], unique=False)
    op.create_index(op.f('ix_test_suites_recording_id'), 'test_suites', ['recording_id'], unique=False)
    op.create_table('generated_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suite_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.Enum('test', 'page_object', 'conftest', 'config', 'fixture', 'util', 'helper', name='file_type'), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suite_id'], ['test_suites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('suite_id', 'path', name='uq_generated_file_path')
    )
    op.create_index(op.f('ix_generated_files_project_id'), 'generated_files', ['project_id'], unique=False)
    op.create_index(op.f('ix_generated_files_suite_id'), 'generated_files', ['suite_id'], unique=False)
    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suite_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('function_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('recording', 'agent', 'manual', name='case_source'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', 'deprecated', name='case_status'), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suite_id'], ['test_suites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cases_project_id'), 'test_cases', ['project_id'], unique=False)
    op.create_index(op.f('ix_test_cases_status'), 'test_cases', ['status'], unique=False)
    op.create_index(op.f('ix_test_cases_suite_id'), 'test_cases', ['suite_id'], unique=False)
    op.create_table('test_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    # action_type was created by the recordings migration. create_type=False
    # references the existing type instead of trying to CREATE it again, which
    # is what autogenerate emits and what breaks a clean `upgrade head`.
    sa.Column('action', postgresql.ENUM(name='action_type', create_type=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('locator', sa.String(length=1024), nullable=True),
    sa.Column('input_data', sa.Text(), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('selector_strategy', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_case_id', 'sequence', name='uq_test_step_sequence')
    )
    op.create_index(op.f('ix_test_steps_test_case_id'), 'test_steps', ['test_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_steps_test_case_id'), table_name='test_steps')
    op.drop_table('test_steps')
    op.drop_index(op.f('ix_test_cases_suite_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_status'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_project_id'), table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index(op.f('ix_generated_files_suite_id'), table_name='generated_files')
    op.drop_index(op.f('ix_generated_files_project_id'), table_name='generated_files')
    op.drop_table('generated_files')
    op.drop_index(op.f('ix_test_suites_recording_id'), table_name='test_suites')
    op.drop_index(op.f('ix_test_suites_project_id'), table_name='test_suites')
    op.drop_table('test_suites')
    # ### end Alembic commands ###

    # Autogenerate creates enum types but never drops them, so without this the
    # next upgrade fails with "type already exists".
    for enum_name in ("file_type", "case_status", "case_source"):
        postgresql.ENUM(name=enum_name, create_type=False).drop(op.get_bind(), checkfirst=True)
