"""current test on run

Revision ID: f174f401b704
Revises: c3f5f25a213d
Create Date: 2026-07-31 17:00:09.443137
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'f174f401b704'
down_revision: str | None = 'c3f5f25a213d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_runs', sa.Column('current_test', sa.String(length=255), nullable=True))
    op.alter_column('test_runs', 'slow_mo_ms',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_runs', 'slow_mo_ms',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_column('test_runs', 'current_test')
    # ### end Alembic commands ###
