"""recording sessions and actions

Revision ID: 4c6d8b58987e
Revises: a1b2c3d4e5f6
Create Date: 2026-07-31 11:04:17.769881
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '4c6d8b58987e'
down_revision: str | None = 'a1b2c3d4e5f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Autogenerate creates enum types but never drops them, so downgrade would
# leave them behind and the next upgrade would fail with "type already exists".
recording_status = postgresql.ENUM(name="recording_status", create_type=False)
action_type = postgresql.ENUM(name="action_type", create_type=False)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recording_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_url', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.Enum('recording', 'completed', 'discarded', name='recording_status'), nullable=False),
    sa.Column('browser_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extension_version', sa.String(length=32), nullable=True),
    sa.Column('action_count', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recording_sessions_created_by_id'), 'recording_sessions', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_recording_sessions_project_id'), 'recording_sessions', ['project_id'], unique=False)
    op.create_index(op.f('ix_recording_sessions_status'), 'recording_sessions', ['status'], unique=False)
    op.create_table('recorded_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('click', 'double_click', 'input', 'select', 'check', 'uncheck', 'hover', 'drag_drop', 'navigate', 'key_press', 'upload', 'scroll', 'assert', name='action_type'), nullable=False),
    sa.Column('timestamp_ms', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('frame_path', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('selectors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('element', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_ignored', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['recording_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'sequence', name='uq_recorded_action_sequence')
    )
    op.create_index(op.f('ix_recorded_actions_session_id'), 'recorded_actions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recorded_actions_session_id'), table_name='recorded_actions')
    op.drop_table('recorded_actions')
    op.drop_index(op.f('ix_recording_sessions_status'), table_name='recording_sessions')
    op.drop_index(op.f('ix_recording_sessions_project_id'), table_name='recording_sessions')
    op.drop_index(op.f('ix_recording_sessions_created_by_id'), table_name='recording_sessions')
    op.drop_table('recording_sessions')
    # ### end Alembic commands ###

    action_type.drop(op.get_bind(), checkfirst=True)
    recording_status.drop(op.get_bind(), checkfirst=True)
